### ISSUE TITLE
Where is Maude 2.6.1?

### ISSUE THREAD

**Issue by peti** [maude-team/full-maude#2]
The full-maude source files say that they ought to be run with Maude version 2.6.1. Where can I find that version?

**Comment by peti** [comment]
Duh, I just discovered the maude repository here on Github, which is at 2.7 already! It's really a shame that this stuff is so hard to find. The web site at http://maude.cs.uiuc.edu/download/ seems hopelessly outdated. 😞

**Comment by narudocap** [comment]
I think you're looking to old pages. Try http://maude.cs.illinois.edu/. http://maude.cs.uiuc.edu/ forwards you to the new site, but not the internal pages, which were left there if anyone needed old versions. May I ask how did you get to http://maude.cs.uiuc.edu/download/?

**Comment by peti** [comment]
That page is the first hit when I search Google for "maude download".
